import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import identityRouter from "./identity.js";
import creditRouter from "./credit.js";
import loansRouter from "./loans.js";
import riskRouter from "./risk.js";
import consentRouter from "./consent.js";
import tenantsRouter from "./tenants.js";
import analyticsRouter from "./analytics.js";
import integrationsRouter from "./integrations.js";
import auditRouter from "./audit.js";
import adminExtendedRouter from "./admin-extended.js";
import adminManagementRouter from "./admin-management.js";
import adminConsumerCreditRouter from "./admin-consumer-credit.js";
import adminDataEcosystemRouter from "./admin-data-ecosystem.js";
import adminOperationsRouter from "./admin-operations.js";
import adminRiskIntelligenceRouter from "./admin-risk-intelligence.js";
import adminAdministrationRouter from "./admin-administration.js";
import adminCommercialRouter from "./admin-commercial.js";
import adminScorecardsRouter from "./admin-scorecards.js";
import { auditTrail } from "../middlewares/audit-trail.js";
import tenantExtendedRouter from "./tenant-extended.js";
import tenantCreditRouter from "./tenant-credit.js";
import tenantWatchlistsRouter from "./tenant-watchlists.js";
import tenantEarlyWarningsRouter from "./tenant-early-warnings.js";
import tenantDisputesRouter from "./tenant-disputes.js";
import tenantComplianceRouter from "./tenant-compliance.js";
import tenantPortfolioAlertsRouter from "./tenant-portfolio-alerts.js";
import tenantBillingRouter from "./tenant-billing.js";
import tenantDataRouter from "./tenant-data.js";
import tenantApiRouter from "./tenant-api.js";
import tenantAdminRouter from "./tenant-admin.js";
import customerPortalRouter from "./customer-portal.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/identity", identityRouter);
router.use("/credit-score", creditRouter);
router.use("/loan-exposure", loansRouter);
router.use("/risk-profile", riskRouter);
router.use("/consent", consentRouter);
router.use("/tenants", tenantsRouter);
router.use("/analytics", analyticsRouter);
router.use("/integrations", integrationsRouter);
router.use("/audit-logs", auditRouter);
router.use("/admin", auditTrail);
router.use("/admin", adminScorecardsRouter);
router.use("/admin", adminExtendedRouter);
router.use("/admin", adminManagementRouter);
router.use("/admin", adminConsumerCreditRouter);
router.use("/admin", adminDataEcosystemRouter);
router.use("/admin", adminOperationsRouter);
router.use("/admin", adminRiskIntelligenceRouter);
router.use("/admin", adminAdministrationRouter);
router.use("/admin", adminCommercialRouter);
router.use("/tenant", tenantExtendedRouter);
router.use("/tenant", tenantCreditRouter);
router.use("/tenant", tenantWatchlistsRouter);
router.use("/tenant", tenantEarlyWarningsRouter);
router.use("/tenant", tenantDisputesRouter);
router.use("/tenant", tenantComplianceRouter);
router.use("/tenant", tenantPortfolioAlertsRouter);
router.use("/tenant", tenantBillingRouter);
router.use("/tenant", tenantDataRouter);
router.use("/tenant", tenantApiRouter);
router.use("/tenant", tenantAdminRouter);
router.use("/customer", customerPortalRouter);

export default router;
